---
- name: Restart EpicBook app process
  command: pm2 restart epicbook
  args:
    chdir: "{{ app_dest }}"
  become: true
  become_user: "{{ app_user }}"
  environment:
    PM2_HOME: /var/www/.pm2
  listen: Restart EpicBook app

- name: Save PM2 process list
  command: pm2 save
  become: true
  become_user: "{{ app_user }}"
  changed_when: false
  environment:
    PM2_HOME: /var/www/.pm2
  listen: Restart EpicBook app
